const fs = require('fs');
const path = require('path');

const docsDirectory = path.join(__dirname, 'docs');
const folders = fs.readdirSync(docsDirectory);

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {};

folders.forEach((folder) => {
    console.log("adding sidebar: " + folder);
    if (fs.statSync(path.join(docsDirectory, folder)).isDirectory()) {
        sidebars[folder] = [{type: 'autogenerated', dirName: folder}];
    }
});

module.exports = sidebars;
