const fs = require('fs');
const path = require('path');

const docsDirectory = path.join(__dirname, 'docs');
const projects = fs.readdirSync(docsDirectory);

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {};

function fileExists(path) {
    try {
        return fs.statSync(path).isFile();
    } catch {
        return false;
    }
}

projects.forEach((project) => {
    console.log("adding sidebar: " + project);
    const docsDir = path.join(docsDirectory, project);
    if (fs.statSync(docsDir).isDirectory()) {
        console.log("docsDir is a directory:", docsDir)
        const categoryFile = path.join(docsDir, "_category_.json");
        console.log("categoryFile:", categoryFile)
        if(fileExists(categoryFile)) {
            const category = require(categoryFile);
            sidebars[project] = [category.link];
        } else {
            console.log("no _category_.json file:", docsDir)
            sidebars[project] = [{type: 'autogenerated', dirName: project}];
        }
    }
});

module.exports = sidebars;
